name: Check Owned Server

on:
  push:
    branches: [owned]
  pull_request:
    branches: [owned]

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'wugan666/komari'
    uses: ./.github/workflows/build-platforms.yml
    with:
      version: 0.0.0-dev
